name: CI/CD Frontend

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.sha }}
  ECS_CLUSTER: tienda-perritos-cluster
  ECS_SERVICE: tienda-perritos-frontend-task-service-pdg5eeup
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login en Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push de la imagen (con BACKEND_URL inyectada)
        env:
          REPO_URI: ${{ secrets.ECR_REPOSITORY_URI }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          docker build \
            --build-arg BACKEND_URL=$BACKEND_URL \
            -t $REPO_URI:$IMAGE_TAG -t $REPO_URI:latest .
          docker push $REPO_URI:$IMAGE_TAG
          docker push $REPO_URI:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Forzar nuevo despliegue en ECS Fargate
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment

      - name: Esperar a que el servicio quede estable
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE
