name: Deploy Frontend to EC2

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tienda-frontend:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_FRONTEND_HOST }}
        username: ec2-user     
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/tienda-perritos-frontend
          
          # 1. Forzar a git a reiniciarse e igualar a la rama remota (evita el error fatal de ramas divergentes)
          git fetch origin deploy
          git reset --hard origin/deploy
          
          cd frontend
          export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          
          # 2. Detener por completo lo que esté usando docker compose
          docker compose down --remove-orphans || true
          
          # 3. Descargar la versión más nueva de la imagen
          docker compose pull
          
          # 4. Levantar el contenedor limpio
          docker compose up -d
