name: Deploy Frontend to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tienda-frontend:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_FRONTEND_HOST }}
        username: ec2-user     
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/tienda-perritos-frontend
          git pull origin deploy
          cd frontend
          export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          docker compose down || docker-compose down || true
          docker compose pull || docker-compose pull
          docker compose up -d || docker-compose up -d
